package tzdata

var CityToIanaTimezone = map[string]map[string]string{
	"Niue":              {"tz": "Pacific/Niue", "country": "Niue"},
	"Midway":            {"tz": "Pacific/Midway", "country": "United States Minor Outlying Islands"},
	"Pago Pago":         {"tz": "Pacific/Pago_Pago", "country": "American Samoa"},
	"Rarotonga":         {"tz": "Pacific/Rarotonga", "country": "Cook Islands"},
	"Adak":              {"tz": "America/Adak", "country": "United States of America"},
	"Honolulu":          {"tz": "Pacific/Honolulu", "country": "United States of America"},
	"Tahiti":            {"tz": "Pacific/Tahiti", "country": "French Polynesia"},
	"Taiohae":           {"tz": "Pacific/Marquesas", "country": "French Polynesia"},
	"Anchorage":         {"tz": "America/Anchorage", "country": "United States of America"},
	"Rikitea":           {"tz": "Pacific/Gambier", "country": "French Polynesia"},
	"Los Angeles":       {"tz": "America/Los_Angeles", "country": "United States of America"},
	"Tijuana":           {"tz": "America/Tijuana", "country": "Mexico"},
	"Vancouver":         {"tz": "America/Vancouver", "country": "Canada"},
	"Adamstown":         {"tz": "Pacific/Pitcairn", "country": "Pitcairn Islands"},
	"Hermosillo":        {"tz": "America/Hermosillo", "country": "Mexico"},
	"Edmonton":          {"tz": "America/Edmonton", "country": "Canada"},
	"Ciudad Juarez":     {"tz": "America/Ciudad_Juarez", "country": "Mexico"},
	"Denver":            {"tz": "America/Denver", "country": "United States of America"},
	"Phoenix":           {"tz": "America/Phoenix", "country": "United States of America"},
	"Whitehorse":        {"tz": "America/Whitehorse", "country": "Canada"},
	"Belize":            {"tz": "America/Belize", "country": "Belize"},
	"Chicago":           {"tz": "America/Chicago", "country": "United States of America"},
	"Guatemala":         {"tz": "America/Guatemala", "country": "Guatemala"},
	"Managua":           {"tz": "America/Managua", "country": "Nicaragua"},
	"Mexico City":       {"tz": "America/Mexico_City", "country": "Mexico"},
	"Matamoros":         {"tz": "America/Matamoros", "country": "Mexico"},
	"Costa Rica":        {"tz": "America/Costa_Rica", "country": "Costa Rica"},
	"El Salvador":       {"tz": "America/El_Salvador", "country": "El Salvador"},
	"Regina":            {"tz": "America/Regina", "country": "Canada"},
	"Tegucigalpa":       {"tz": "America/Tegucigalpa", "country": "Honduras"},
	"Winnipeg":          {"tz": "America/Winnipeg", "country": "Canada"},
	"Easter Island":     {"tz": "Pacific/Easter", "country": "Chile"},
	"Galapagos":         {"tz": "Pacific/Galapagos", "country": "Ecuador"},
	"Rio Branco":        {"tz": "America/Rio_Branco", "country": "Brazil"},
	"Bogota":            {"tz": "America/Bogota", "country": "Colombia"},
	"Havana":            {"tz": "America/Havana", "country": "Cuba"},
	"Atikokan":          {"tz": "America/Atikokan", "country": "Canada"},
	"Cancun":            {"tz": "America/Cancun", "country": "Mexico"},
	"Cockburn Town":     {"tz": "America/Grand_Turk", "country": "Turks and Caicos Island"},
	"George Town":       {"tz": "America/Cayman", "country": "Cayman Islands"},
	"Jamaica":           {"tz": "America/Jamaica", "country": "Jamaica"},
	"Nassau":            {"tz": "America/Nassau", "country": "Bahamas"},
	"New York":          {"tz": "America/New_York", "country": "United States of America"},
	"Panama":            {"tz": "America/Panama", "country": "Panama"},
	"Port-au-Prince":    {"tz": "America/Port-au-Prince", "country": "Haiti"},
	"Toronto":           {"tz": "America/Toronto", "country": "Canada"},
	"Guayaquil":         {"tz": "America/Guayaquil", "country": "Ecuador"},
	"Lima":              {"tz": "America/Lima", "country": "Peru"},
	"Manaus":            {"tz": "America/Manaus", "country": "Brazil"},
	"Basseterre":        {"tz": "America/St_Kitts", "country": "Saint Kitts and Nevis"},
	"Blanc-Sablon":      {"tz": "America/Blanc-Sablon", "country": "Canada"},
	"Plymouth":          {"tz": "America/Montserrat", "country": "Montserrat"},
	"Barbados":          {"tz": "America/Barbados", "country": "Barbados"},
	"Port of Spain":     {"tz": "America/Port_of_Spain", "country": "Trinidad and Tobago"},
	"Martinique":        {"tz": "America/Martinique", "country": "France"},
	"Castries":          {"tz": "America/St_Lucia", "country": "Saint Lucia"},
	"Gustavia":          {"tz": "America/St_Barthelemy", "country": "Saint Barthelemy"},
	"Halifax":           {"tz": "America/Halifax", "country": "Canada"},
	"Hamilton":          {"tz": "Atlantic/Bermuda", "country": "Bermuda"},
	"Kingstown":         {"tz": "America/St_Vincent", "country": "Saint Vincent and the Grenadines"},
	"Kralendijk":        {"tz": "America/Kralendijk", "country": "Bonaire"},
	"Basse-Terre":        {"tz": "America/Guadeloupe", "country": "Guadeloupe"},
	"Marigot":           {"tz": "America/Marigot", "country": "France"},
	"Oranjestad":        {"tz": "America/Aruba", "country": "Aruba"},
	"Lower Princes":     {"tz": "America/Lower_Princes", "country": "Sint Maarten"},
	"Tortola":           {"tz": "America/Tortola", "country": "United Kingdom"},
	"Roseau":            {"tz": "America/Dominica", "country": "Dominica"},
	"Charlotte Amalie":  {"tz": "America/St_Thomas", "country": "United States Virgin Islands"},
	"Road Town":         {"tz": "America/Tortola", "country": "British Virgin Islands"},
	"St Georges":        {"tz": "America/Grenada", "country": "Grenada"},
	"Antigua":           {"tz": "America/Antigua", "country": "Antigua and Barbuda"},
	"Puerto Rico":       {"tz": "America/Puerto_Rico", "country": "Puerto Rico"},
	"Santo Domingo":     {"tz": "America/Santo_Domingo", "country": "Dominican Republic"},
	"The Valley":        {"tz": "America/Anguilla", "country": "Anguilla"},
	"Thule":             {"tz": "America/Thule", "country": "Greenland"},
	"Willemstad":        {"tz": "America/Curacao", "country": "Curacao"},
	"La Paz":            {"tz": "America/La_Paz", "country": "Bolivia"},
	"Santiago":          {"tz": "America/Santiago", "country": "Chile"},
	"Guyana":            {"tz": "America/Guyana", "country": "Guyana"},
	"Asuncion":          {"tz": "America/Asuncion", "country": "Paraguay"},
	"Caracas":           {"tz": "America/Caracas", "country": "Venezuela"},
	"St Johns":          {"tz": "America/St_Johns", "country": "Canada"},
	"Buenos Aires":      {"tz": "America/Argentina/Buenos_Aires", "country": "Argentina"},
	"Sao Paulo":         {"tz": "America/Sao_Paulo", "country": "Brazil"},
	"Palmer":            {"tz": "Antarctica/Palmer", "country": "Antarctica"},
	"Punta Arenas":      {"tz": "America/Punta_Arenas", "country": "Chile"},
	"Stanley":           {"tz": "Atlantic/Stanley", "country": "Falkland Islands"},
	"Cayenne":           {"tz": "America/Cayenne", "country": "French Guiana"},
	"Miquelon":          {"tz": "America/Miquelon", "country": "France"},
	"Paramaribo":        {"tz": "America/Paramaribo", "country": "Suriname"},
	"Montevideo":        {"tz": "America/Montevideo", "country": "Uruguay"},
	"Ittoqqortoormiit":  {"tz": "America/Scoresbysund", "country": "Greenland"},
	"Noronha":           {"tz": "America/Noronha", "country": "Brazil"},
	"King Edward Point": {"tz": "Atlantic/South_Georgia", "country": "South Georgia and the South Sandwich Islands"},
	"Nuuk":              {"tz": "America/Nuuk", "country": "Greenland"},
	"Azores":            {"tz": "Atlantic/Azores", "country": "Portugal"},
	"Cape_Verde":        {"tz": "Atlantic/Cape_Verde", "country": "Cape Verde"},
	"Abidjan":           {"tz": "Africa/Abidjan", "country": "Ivory Coast"},
	"Bamako":            {"tz": "Africa/Bamako", "country": "Mali"},
	"Bissau":            {"tz": "Africa/Bissau", "country": "Guinea-Bissau"},
	"Conakry":           {"tz": "Africa/Conakry", "country": "Guinea"},
	"Dakar":             {"tz": "Africa/Dakar", "country": "Senegal"},
	"Danmarkshavn":      {"tz": "America/Danmarkshavn", "country": "Greenland"},
	"Douglas":           {"tz": "Europe/Isle_of_Man", "country": "Isle of Man"},
	"Dublin":            {"tz": "Europe/Dublin", "country": "Ireland"},
	"Freetown":          {"tz": "Africa/Freetown", "country": "Sierra Leone"},
	"Jamestown":         {"tz": "Atlantic/St_Helena", "country": "Saint Helena, Ascension and Tristan da Cunha"},
	"Accra":             {"tz": "Africa/Accra", "country": "Ghana"},
	"Lome":              {"tz": "Africa/Lome", "country": "Togo"},
	"London":            {"tz": "Europe/London", "country": "United Kingdom"},
	"Monrovia":          {"tz": "Africa/Monrovia", "country": "Liberia"},
	"Nouakchott":        {"tz": "Africa/Nouakchott", "country": "Mauritania"},
	"Ouagadougou":       {"tz": "Africa/Ouagadougou", "country": "Burkina Faso"},
	"Reykjavik":         {"tz": "Atlantic/Reykjavik", "country": "Iceland"},
	"St Helier":         {"tz": "Europe/Jersey", "country": "Jersey"},
	"St Peter Port":     {"tz": "Europe/Guernsey", "country": "Guernsey"},
	"Banjul":            {"tz": "Africa/Banjul", "country": "Gambia"},
	"Sao Tome":          {"tz": "Africa/Sao_Tome", "country": "Sao Tome and Principe"},
	"Troll":             {"tz": "Antarctica/Troll", "country": "Antarctica"},
	"Casablanca":        {"tz": "Africa/Casablanca", "country": "Morocco"},
	"El Aaiun":          {"tz": "Africa/El_Aaiun", "country": "Western Sahara"},
	"Canary":            {"tz": "Atlantic/Canary", "country": "Spain"},
	"Lisbon":            {"tz": "Europe/Lisbon", "country": "Portugal"},
	"Torshavn":          {"tz": "Atlantic/Faroe", "country": "Faroe Islands"},
	"Windhoek":          {"tz": "Africa/Windhoek", "country": "Namibia"},
	"Algiers":           {"tz": "Africa/Algiers", "country": "Algeria"},
	"Amsterdam":         {"tz": "Europe/Amsterdam", "country": "Netherlands"},
	"Andorra la Vella":  {"tz": "Europe/Andorra", "country": "Andorra"},
	"Belgrade":          {"tz": "Europe/Belgrade", "country": "Serbia"},
	"Berlin":            {"tz": "Europe/Berlin", "country": "Germany"},
	"Bratislava":        {"tz": "Europe/Bratislava", "country": "Slovakia"},
	"Brussels":          {"tz": "Europe/Brussels", "country": "Belgium"},
	"Budapest":          {"tz": "Europe/Budapest", "country": "Hungary"},
	"Copenhagen":        {"tz": "Europe/Copenhagen", "country": "Denmark"},
	"Gibraltar":         {"tz": "Europe/Gibraltar", "country": "United Kingdom"},
	"Ljubljana":         {"tz": "Europe/Ljubljana", "country": "Slovenia"},
	"Longyearbyen":      {"tz": "Arctic/Longyearbyen", "country": "Svalbard and Jan Mayen"},
	"Luxembourg":        {"tz": "Europe/Luxembourg", "country": "Luxembourg"},
	"Madrid":            {"tz": "Europe/Madrid", "country": "Spain"},
	"Monaco":            {"tz": "Europe/Monaco", "country": "Monaco"},
	"Oslo":              {"tz": "Europe/Oslo", "country": "Norway"},
	"Paris":             {"tz": "Europe/Paris", "country": "France"},
	"Podgorica":         {"tz": "Europe/Podgorica", "country": "Montenegro"},
	"Prague":            {"tz": "Europe/Prague", "country": "Czech Republic"},
	"Rome":              {"tz": "Europe/Rome", "country": "Italy"},
	"San Marino":        {"tz": "Europe/San_Marino", "country": "San Marino"},
	"Malta":             {"tz": "Europe/Malta", "country": "Malta"},
	"Sarajevo":          {"tz": "Europe/Sarajevo", "country": "Bosnia and Herzegovina"},
	"Skopje":            {"tz": "Europe/Skopje", "country": "North Macedonia"},
	"Stockholm":         {"tz": "Europe/Stockholm", "country": "Sweden"},
	"Tirane":            {"tz": "Europe/Tirane", "country": "Albania"},
	"Tunis":             {"tz": "Africa/Tunis", "country": "Tunisia"},
	"Vaduz":             {"tz": "Europe/Vaduz", "country": "Liechtenstein"},
	"Vatican":           {"tz": "Europe/Vatican", "country": "Vatican City"},
	"Vienna":            {"tz": "Europe/Vienna", "country": "Austria"},
	"Warsaw":            {"tz": "Europe/Warsaw", "country": "Poland"},
	"Zagreb":            {"tz": "Europe/Zagreb", "country": "Croatia"},
	"Zurich":            {"tz": "Europe/Zurich", "country": "Switzerland"},
	"Bangui":            {"tz": "Africa/Bangui", "country": "Central African Republic"},
	"Malabo":            {"tz": "Africa/Malabo", "country": "Equatorial Guinea"},
	"Brazzaville":       {"tz": "Africa/Brazzaville", "country": "Republic of the Congo"},
	"Porto-Novo":        {"tz": "Africa/Porto-Novo", "country": "Benin"},
	"Douala":            {"tz": "Africa/Douala", "country": "Cameroon"},
	"Kinshasa":          {"tz": "Africa/Kinshasa", "country": "Democratic Republic of the Congo"},
	"Lagos":             {"tz": "Africa/Lagos", "country": "Nigeria"},
	"Libreville":        {"tz": "Africa/Libreville", "country": "Gabon"},
	"Luanda":            {"tz": "Africa/Luanda", "country": "Angola"},
	"Ndjamena":          {"tz": "Africa/Ndjamena", "country": "Chad"},
	"Niamey":            {"tz": "Africa/Niamey", "country": "Niger"},
	"Bujumbura":         {"tz": "Africa/Bujumbura", "country": "Burundi"},
	"Gaborone":          {"tz": "Africa/Gaborone", "country": "Botswana"},
	"Harare":            {"tz": "Africa/Harare", "country": "Zimbabwe"},
	"Juba":              {"tz": "Africa/Juba", "country": "South Sudan"},
	"Khartoum":          {"tz": "Africa/Khartoum", "country": "Sudan"},
	"Kigali":            {"tz": "Africa/Kigali", "country": "Rwanda"},
	"Blantyre":          {"tz": "Africa/Blantyre", "country": "Malawi"},
	"Lubumbashi":        {"tz": "Africa/Lubumbashi", "country": "Democratic Republic of the Congo"},
	"Lusaka":            {"tz": "Africa/Lusaka", "country": "Zambia"},
	"Maputo":            {"tz": "Africa/Maputo", "country": "Mozambique"},
	"Athens":            {"tz": "Europe/Athens", "country": "Greece"},
	"Beirut":            {"tz": "Asia/Beirut", "country": "Lebanon"},
	"Bucharest":         {"tz": "Europe/Bucharest", "country": "Romania"},
	"Cairo":             {"tz": "Africa/Cairo", "country": "Egypt"},
	"Chisinau":          {"tz": "Europe/Chisinau", "country": "Moldova"},
	"Hebron":            {"tz": "Asia/Hebron", "country": "Palestine"},
	"Helsinki":          {"tz": "Europe/Helsinki", "country": "Finland"},
	"Kaliningrad":       {"tz": "Europe/Kaliningrad", "country": "Russia"},
	"Kyiv":              {"tz": "Europe/Kyiv", "country": "Ukraine"},
	"Mariehamn":         {"tz": "Europe/Mariehamn", "country": "Aland Islands"},
	"Nicosia":           {"tz": "Asia/Nicosia", "country": "Cyprus"},
	"Riga":              {"tz": "Europe/Riga", "country": "Latvia"},
	"Sofia":             {"tz": "Europe/Sofia", "country": "Bulgaria"},
	"Tallinn":           {"tz": "Europe/Tallinn", "country": "Estonia"},
	"Tripoli":           {"tz": "Africa/Tripoli", "country": "Libya"},
	"Vilnius":           {"tz": "Europe/Vilnius", "country": "Lithuania"},
	"Jerusalem":         {"tz": "Asia/Jerusalem", "country": "Israel"},
	"Johannesburg":      {"tz": "Africa/Johannesburg", "country": "South Africa"},
	"Mbabane":           {"tz": "Africa/Mbabane", "country": "Eswatini"},
	"Maseru":            {"tz": "Africa/Maseru", "country": "Lesotho"},
	"Kuwait":            {"tz": "Asia/Kuwait", "country": "Kuwait"},
	"Bahrain":           {"tz": "Asia/Bahrain", "country": "Bahrain"},
	"Baghdad":           {"tz": "Asia/Baghdad", "country": "Iraq"},
	"Qatar":             {"tz": "Asia/Qatar", "country": "Qatar"},
	"Riyadh":            {"tz": "Asia/Riyadh", "country": "Saudi Arabia"},
	"Aden":              {"tz": "Asia/Aden", "country": "Yemen"},
	"Amman":             {"tz": "Asia/Amman", "country": "Jordan"},
	"Damascus":          {"tz": "Asia/Damascus", "country": "Syria"},
	"Addis Ababa":       {"tz": "Africa/Addis_Ababa", "country": "Ethiopia"},
	"Antananarivo":      {"tz": "Indian/Antananarivo", "country": "Madagascar"},
	"Asmara":            {"tz": "Africa/Asmara", "country": "Eritrea"},
	"Dar es Salaam":     {"tz": "Africa/Dar_es_Salaam", "country": "Tanzania"},
	"Djibouti":          {"tz": "Africa/Djibouti", "country": "Djibouti"},
	"Kampala":           {"tz": "Africa/Kampala", "country": "Uganda"},
	"Mamoudzou":         {"tz": "Indian/Mayotte", "country": "Mayotte"},
	"Mogadishu":         {"tz": "Africa/Mogadishu", "country": "Somalia"},
	"Comoro":            {"tz": "Indian/Comoro", "country": "Comoros"},
	"Nairobi":           {"tz": "Africa/Nairobi", "country": "Kenya"},
	"Minsk":             {"tz": "Europe/Minsk", "country": "Belarus"},
	"Moscow":            {"tz": "Europe/Moscow", "country": "Russia"},
	"Simferopol":        {"tz": "Europe/Simferopol", "country": "Ukraine"},
	"Syowa":             {"tz": "Antarctica/Syowa", "country": "Antarctica"},
	"Istanbul":          {"tz": "Europe/Istanbul", "country": "Turkey"},
	"Tehran":            {"tz": "Asia/Tehran", "country": "Iran"},
	"Yerevan":           {"tz": "Asia/Yerevan", "country": "Armenia"},
	"Baku":              {"tz": "Asia/Baku", "country": "Azerbaijan"},
	"Tbilisi":           {"tz": "Asia/Tbilisi", "country": "Georgia"},
	"Dubai":             {"tz": "Asia/Dubai", "country": "United Arab Emirates"},
	"Muscat":            {"tz": "Asia/Muscat", "country": "Oman"},
	"Mauritius":         {"tz": "Indian/Mauritius", "country": "Mauritius"},
	"Saint-Denis":       {"tz": "Indian/Reunion", "country": "Reunion"},
	"Samara":            {"tz": "Europe/Samara", "country": "Russia"},
	"Mahe":              {"tz": "Indian/Mahe", "country": "Seychelles"},
	"Kabul":             {"tz": "Asia/Kabul", "country": "Afghanistan"},
	"Almaty":            {"tz": "Asia/Almaty", "country": "Kazakhstan"},
	"Port-aux-Francais": {"tz": "Indian/Kerguelen", "country": "French Southern and Antarctic Lands"},
	"Maldives":          {"tz": "Indian/Maldives", "country": "Maldives"},
	"Mawson":            {"tz": "Antarctica/Mawson", "country": "Antarctica"},
	"Karachi":           {"tz": "Asia/Karachi", "country": "Pakistan"},
	"Dushanbe":          {"tz": "Asia/Dushanbe", "country": "Tajikistan"},
	"Ashgabat":          {"tz": "Asia/Ashgabat", "country": "Turkmenistan"},
	"Tashkent":          {"tz": "Asia/Tashkent", "country": "Uzbekistan"},
	"Aqtobe":            {"tz": "Asia/Aqtobe", "country": "Kazakhstan"},
	"Yekaterinburg":     {"tz": "Asia/Yekaterinburg", "country": "Russia"},
	"Colombo":           {"tz": "Asia/Colombo", "country": "Sri Lanka"},
	"Kolkata":           {"tz": "Asia/Kolkata", "country": "India"},
	"Kathmandu":         {"tz": "Asia/Kathmandu", "country": "Nepal"},
	"Dhaka":             {"tz": "Asia/Dhaka", "country": "Bangladesh"},
	"Thimphu":           {"tz": "Asia/Thimphu", "country": "Bhutan"},
	"Urumqi":            {"tz": "Asia/Urumqi", "country": "China"},
	"Diego Garcia":      {"tz": "Indian/Chagos", "country": "British Indian Ocean Territory"},
	"Bishkek":           {"tz": "Asia/Bishkek", "country": "Kyrgyzstan"},
	"Omsk":              {"tz": "Asia/Omsk", "country": "Russia"},
	"Bantam Village":    {"tz": "Indian/Cocos", "country": "Cocos (Keeling) Island"},
	"Yangon":            {"tz": "Asia/Yangon", "country": "Myanmar"},
	"Flying Fish Cove":  {"tz": "Indian/Christmas", "country": "Christmas Island"},
	"Davis":             {"tz": "Antarctica/Davis", "country": "Antarctica"},
	"Hovd":              {"tz": "Asia/Hovd", "country": "Mongolia"},
	"Choibalsan":        {"tz": "Asia/Choibalsan", "country": "Mongolia"},
	"Bangkok":           {"tz": "Asia/Bangkok", "country": "Thailand"},
	"Ho Chi Minh":       {"tz": "Asia/Ho_Chi_Minh", "country": "Vietnam"},
	"Phnom Penh":        {"tz": "Asia/Phnom_Penh", "country": "Cambodia"},
	"Vientiane":         {"tz": "Asia/Vientiane", "country": "Laos"},
	"Novosibirsk":       {"tz": "Asia/Novosibirsk", "country": "Russia"},
	"Jakarta":           {"tz": "Asia/Jakarta", "country": "Indonesia"},
	"Casey":             {"tz": "Antarctica/Casey", "country": "Antarctica"},
	"Perth":             {"tz": "Australia/Perth", "country": "Australia"},
	"Brunei":            {"tz": "Asia/Brunei", "country": "Brunei"},
	"Makassar":          {"tz": "Asia/Makassar", "country": "Indonesia"},
	"Macao":             {"tz": "Asia/Macau", "country": "Macao"},
	"Shanghai":          {"tz": "Asia/Shanghai", "country": "China"},
	"Hong Kong":         {"tz": "Asia/Hong_Kong", "country": "Hong Kong"},
	"Irkutsk":           {"tz": "Asia/Irkutsk", "country": "Russia"},
	"Kuala Lumpur":      {"tz": "Asia/Kuala_Lumpur", "country": "Malaysia"},
	"Manila":            {"tz": "Asia/Manila", "country": "Philippines"},
	"Singapore":         {"tz": "Asia/Singapore", "country": "Singapore"},
	"Taipei":            {"tz": "Asia/Taipei", "country": "Taiwan"},
	"Ulaanbaatar":       {"tz": "Asia/Ulaanbaatar", "country": "Mongolia"},
	"Eucla":             {"tz": "Australia/Eucla", "country": "Australia"},
	"Dili":              {"tz": "Asia/Dili", "country": "Timor-Leste"},
	"Jayapura":          {"tz": "Asia/Jayapura", "country": "Indonesia"},
	"Tokyo":             {"tz": "Asia/Tokyo", "country": "Japan"},
	"Pyongyang":         {"tz": "Asia/Pyongyang", "country": "North Korea"},
	"Seoul":             {"tz": "Asia/Seoul", "country": "South Korea"},
	"Koror":             {"tz": "Pacific/Palau", "country": "Palau"},
	"Chita":             {"tz": "Asia/Chita", "country": "Russia"},
	"Adelaide":          {"tz": "Australia/Adelaide", "country": "Australia"},
	"Darwin":            {"tz": "Australia/Darwin", "country": "Australia"},
	"Brisbane":          {"tz": "Australia/Brisbane", "country": "Australia"},
	"Sydney":            {"tz": "Australia/Sydney", "country": "Australia"},
	"Guam":              {"tz": "Pacific/Guam", "country": "Guam"},
	"Saipan":            {"tz": "Pacific/Saipan", "country": "Northern Mariana Islands"},
	"Chuuk":             {"tz": "Pacific/Chuuk", "country": "Micronesia"},
	"Pohnpei":           {"tz": "Pacific/Pohnpei", "country": "Micronesia"},
	"Dumont d'Urville":  {"tz": "Antarctica/DumontDUrville", "country": "Antarctica"},
	"Port Moresby":      {"tz": "Pacific/Port_Moresby", "country": "Papua New Guinea"},
	"Vladivostok":       {"tz": "Asia/Vladivostok", "country": "Russia"},
	"Lord Howe":         {"tz": "Australia/Lord_Howe", "country": "Australia"},
	"Bougainville":      {"tz": "Pacific/Bougainville", "country": "Papua New Guinea"},
	"Kosrae":            {"tz": "Pacific/Kosrae", "country": "Micronesia"},
	"Noumea":            {"tz": "Pacific/Noumea", "country": "New Caledonia"},
	"Kingston":          {"tz": "Pacific/Norfolk", "country": "Norfold Island"},
	"Sakhalin":          {"tz": "Asia/Sakhalin", "country": "Russia"},
	"Honiara":           {"tz": "Pacific/Guadalcanal", "country": "Solomon Islands"},
	"Efate":             {"tz": "Pacific/Efate", "country": "Vanuatu"},
	"Suva":              {"tz": "Pacific/Fiji", "country": "Fiji"},
	"Tarawa":            {"tz": "Pacific/Tarawa", "country": "Kiribati"},
	"Majuro":            {"tz": "Pacific/Majuro", "country": "Marshall Islands"},
	"Nauru":             {"tz": "Pacific/Nauru", "country": "Nauru"},
	"Auckland":          {"tz": "Pacific/Auckland", "country": "New Zealand"},
	"McMurdo":           {"tz": "Antarctica/McMurdo", "country": "Antarctica"},
	"Vostok":           {"tz": "Antarctica/Vostok", "country": "Antarctica"},
	"Kamchatka":         {"tz": "Asia/Kamchatka", "country": "Russia"},
	"Funafuti":          {"tz": "Pacific/Funafuti", "country": "Tuvalu"},
	"Mata-utu":          {"tz": "Pacific/Wallis", "country": "Wallis and Futuna"},
	"Chatham":           {"tz": "Pacific/Chatham", "country": "New Zealand"},
	"Apia":              {"tz": "Pacific/Apia", "country": "Samoa"},
	"Kanton":            {"tz": "Pacific/Kanton", "country": "Kiribati"},
	"Fale":              {"tz": "Pacific/Fakaofo", "country": "Tokelau"},
	"Nuku'alofa":        {"tz": "Pacific/Tongatapu", "country": "Tonga"},
	"Kiritimati":        {"tz": "Pacific/Kiritimati", "country": "Kiribati"},
}
