package tzdata

var CountryToIanaTimezone = map[string][]string{
	"Afghanistan": {"Asia/Kabul"},
	"Albania":     {"Europe/Tirane"},
	"Algeria":     {"Africa/Algiers"},
	"Andorra":     {"Europe/Andorra"},
	"Angola":      {"Africa/Luanda"},
	"Anguilla":    {"America/Anguilla"},
	"Antarctica": {
		"Antarctica/Casey", "Antarctica/Davis", "Antarctica/DumontDUrville",
		"Antarctica/Mawson", "Antarctica/McMurdo", "Antarctica/Palmer",
		"Antarctica/Rothera", "Antarctica/Syowa", "Antarctica/Troll",
		"Antarctica/    ostok",
	},
	"Antigua and Barbuda": {"America/Antigua"},
	"Argentina": {
		"America/Argentina/Buenos_Aires", "America/Buenos_Aires",
		"America/Argentina/Catamarca", "America/Argentina/Cordoba",
		"America/Argentina/Jujuy", "America/Argentina/La_Rioja",
		"America/Argentina/Mendoza", "America/Argentina/Rio_Gallegos",
		"America/Argentina/Salta", "America/Argentina/San_Juan",
		"America/Argentina/San_Luis", "America/Argentina/Tucuman",
		"America/Argentina/Ushuaia",
	},
	"Armenia": {"Asia/Yerevan"},
	"Aruba":   {"America/Aruba"},
	"Australia": {
		"Antarctica/Macquarie", "Australia/Adelaide", "Australia/Brisbane",
		"Australia/Broken_Hill", "Australia/Currie", "Australia/Darwin",
		"Australia/Eucla", "Australia/Hobart", "Australia/Lindeman",
		"Australia/Lord_Howe", "Australia/Melbourne", "Australia/Perth",
		"Australia/Sydney", "Pacific/Norfolk",
	},
	"Austria":                {"Europe/Vienna"},
	"Azerbaijan":             {"Asia/Baku"},
	"Bahamas":                {"America/Nassau"},
	"Bahrain":                {"Asia/Bahrain"},
	"Bangladesh":             {"Asia/Dhaka"},
	"Barbados":               {"America/Barbados"},
	"Belarus":                {"Europe/Minsk"},
	"Belgium":                {"Europe/Brussels"},
	"Belize":                 {"America/Belize"},
	"Benin":                  {"Africa/Porto-Novo"},
	"Bermuda":                {"Atlantic/Bermuda"},
	"Bhutan":                 {"Asia/Thimphu"},
	"Bolivia":                {"America/La_Paz"},
	"Bosnia and Herzegovina": {"Europe/Sarajevo"},
	"Botswana":               {"Africa/Gaborone"},
	"Brazil": {
		"America/Araguaina", "America/Bahia", "America/Belem",
		"America/Boa_Vista", "America/Campo_Grande", "America/Cuiaba",
		"America/Eirunepe", "America/Fortaleza", "America/Maceio",
		"America/Manaus", "America/Noronha", "America/Porto_Velho",
		"America/Recife", "America/Rio_Branco", "America/Santarem",
		"America/Sao_Paulo",
	},
	"Brunei":       {"Asia/Brunei"},
	"Bulgaria":     {"Europe/Sofia"},
	"Burkina Faso": {"Africa/Ouagadougou"},
	"Burundi":      {"Africa/Bujumbura"},
	"Cambodia":     {"Asia/Phnom_Penh"},
	"Cameroon":     {"Africa/Douala"},
	"Canada": {
		"America/Atikokan", "America/Blanc-Sablon", "America/Cambridge_Bay",
		"America/Montreal", "America/Creston", "America/Dawson",
		"America/Dawson_Creek", "America/Edmonton", "America/Fort_Nelson",
		"America/Glace_Bay", "America/Goose_Bay", "America/Halifax",
		"America/Inuvik", "America/Iqaluit", "America/Moncton",
		"America/Nipigon", "America/Pangnirtung", "America/Rainy_River",
		"America/Rankin_Inlet", "America/Regina", "America/Resolute",
		"America/St_Johns", "America/Swift_Current", "America/Thunder_Bay",
		"America/Toronto", "America/Vancouver", "America/Whitehorse",
		"America/Winnipeg", "America/Yellowknife",
	},
	"Cape Verde":               {"Atlantic/Cape_Verde"},
	"Cayman Islands":           {"America/Cayman"},
	"Central African Republic": {"Africa/Bangui"},
	"Chad":                     {"Africa/Ndjamena"},
	"Chile": {
		"America/Punta_Arenas", "America/Santiago", "Pacific/Easter",
	},
	"China":                            {"Asia/Shanghai", "Asia/Urumqi", "Asia/Chungking", "Asia/Chongqing"},
	"Christmas Island":                 {"Indian/Christmas"},
	"Cocos Islands":                    {"Indian/Cocos"},
	"Colombia":                         {"America/Bogota"},
	"Comoros":                          {"Indian/Comoro"},
	"Cook Islands":                     {"Pacific/Rarotonga"},
	"Costa Rica":                       {"America/Costa_Rica"},
	"Croatia":                          {"Europe/Zagreb"},
	"Cuba":                             {"America/Havana"},
	"Curacao":                          {"America/Curacao"},
	"Cyprus":                           {"Asia/Famagusta", "Asia/Nicosia"},
	"Czech Republic":                   {"Europe/Prague"},
	"Democratic Republic of the Congo": {"Africa/Kinshasa", "Africa/Lubumbashi"},
	"Denmark":                          {"Europe/Copenhagen"},
	"Djibouti":                         {"Africa/Djibouti"},
	"Dominica":                         {"America/Dominica"},
	"Dominican Republic":               {"America/Santo_Domingo"},
	"Timor-Leste":                      {"Asia/Dili"},
	"Ecuador":                          {"America/Guayaquil", "Pacific/Galapagos"},
	"Egypt":                            {"Africa/Cairo"},
	"El Salvador":                      {"America/El_Salvador"},
	"Equatorial Guinea":                {"Africa/Malabo"},
	"Eritrea":                          {"Africa/Asmara"},
	"Estonia":                          {"Europe/Tallinn"},
	"Ethiopia":                         {"Africa/Addis_Ababa"},
	"Falkland Islands":                 {"Atlantic/Stanley"},
	"Faroe Islands":                    {"Atlantic/Faroe"},
	"Fiji":                             {"Pacific/Fiji"},
	"Finland":                          {"Europe/Helsinki"},
	"France": {
		"Europe/Paris", "Europe/Monaco", "Indian/Reunion", "Indian/Mayotte",
		"Indian/Kerguelen", "Pacific/Noumea", "Pacific/Wallis", "Pacific/Tahiti",
		"Pacific/Gambier", "Pacific/Marquesas", "America/Guadeloupe", "America/Martinique",
		"America/Cayenne", "America/Miquelon", "Atlantic/St_Helena", "Antarctica/DumontDUrville",
		"Indian/Reunion",
	},
	"Gabon":         {"Africa/Libreville"},
	"Gambia":        {"Africa/Banjul"},
	"Georgia":       {"Asia/Tbilisi"},
	"Germany":       {"Europe/Berlin", "Europe/Busingen"},
	"Ghana":         {"Africa/Accra"},
	"Gibraltar":     {"Europe/Gibraltar"},
	"Greece":        {"Europe/Athens"},
	"Greenland":     {"America/Danmarkshavn", "America/Godthab", "America/Scoresbysund", "America/Thule"},
	"Grenada":       {"America/Grenada"},
	"Guadeloupe":    {"America/Guadeloupe"},
	"Guatemala":     {"America/Guatemala"},
	"Guernsey":      {"Europe/Guernsey"},
	"Guinea":        {"Africa/Conakry"},
	"Guinea-Bissau": {"Africa/Bissau"},
	"Guyana":        {"America/Guyana"},
	"Haiti":         {"America/Port-au-Prince"},
	"Honduras":      {"America/Tegucigalpa"},
	"Hong Kong":     {"Asia/Hong_Kong"},
	"Hungary":       {"Europe/Budapest"},
	"Iceland":       {"Atlantic/Reykjavik"},
	"India":         {"Asia/Kolkata", "Asia/Calcutta"},
	"Indonesia":     {"Asia/Jakarta", "Asia/Jayapura", "Asia/Makassar", "Asia/Pontianak"},
	"Iran":          {"Asia/Tehran"},
	"Iraq":          {"Asia/Baghdad"},
	"Ireland":       {"Europe/Dublin"},
	"Israel":        {"Asia/Jerusalem"},
	"Italy":         {"Europe/Rome"},
	"Ivory Coast":   {"Africa/Abidjan"},
	"Jamaica":       {"America/Jamaica"},
	"Japan":         {"Asia/Tokyo"},
	"Jordan":        {"Asia/Amman"},
	"Kazakhstan": {
		"Asia/Almaty", "Asia/Aqtau", "Asia/Aqtobe", "Asia/Atyrau",
		"Asia/Oral", "Asia/Qyzylorda",
	},
	"Kenya":            {"Africa/Nairobi"},
	"Kiribati":         {"Pacific/Enderbury", "Pacific/Kiritimati", "Pacific/Tarawa"},
	"Kuwait":           {"Asia/Kuwait"},
	"Kyrgyzstan":       {"Asia/Bishkek"},
	"Laos":             {"Asia/Vientiane"},
	"Latvia":           {"Europe/Riga"},
	"Lebanon":          {"Asia/Beirut"},
	"Lesotho":          {"Africa/Maseru"},
	"Liberia":          {"Africa/Monrovia"},
	"Libya":            {"Africa/Tripoli"},
	"Liechtenstein":    {"Europe/Vaduz"},
	"Lithuania":        {"Europe/Vilnius"},
	"Luxembourg":       {"Europe/Luxembourg"},
	"Macao":            {"Asia/Macau"},
	"Macedonia":        {"Europe/Skopje"},
	"Madagascar":       {"Indian/Antananarivo"},
	"Malawi":           {"Africa/Blantyre"},
	"Malaysia":         {"Asia/Kuala_Lumpur", "Asia/Kuching"},
	"Maldives":         {"Indian/Maldives"},
	"Mali":             {"Africa/Bamako"},
	"Malta":            {"Europe/Malta"},
	"Marshall Islands": {"Pacific/Kwajalein", "Pacific/Majuro"},
	"Martinique":       {"America/Martinique"},
	"Mauritania":       {"Africa/Nouakchott"},
	"Mauritius":        {"Indian/Mauritius"},
	"Mayotte":          {"Indian/Mayotte"},
	"Mexico": {
		"America/Bahia_Banderas", "America/Cancun", "America/Chihuahua",
		"America/Hermosillo", "America/Matamoros", "America/Mazatlan",
		"America/Merida", "America/Mexico_City", "America/Monterrey",
		"America/Ojinaga", "America/Tijuana",
	},
	"Micronesia":               {"Pacific/Chuuk", "Pacific/Kosrae", "Pacific/Pohnpei"},
	"Moldova":                  {"Europe/Chisinau"},
	"Monaco":                   {"Europe/Monaco"},
	"Mongolia":                 {"Asia/Choibalsan", "Asia/Hovd", "Asia/Ulaanbaatar"},
	"Montenegro":               {"Europe/Podgorica"},
	"Montserrat":               {"America/Montserrat"},
	"Morocco":                  {"Africa/Casablanca"},
	"Mozambique":               {"Africa/Maputo"},
	"Namibia":                  {"Africa/Windhoek"},
	"Nauru":                    {"Pacific/Nauru"},
	"Nepal":                    {"Asia/Kathmandu"},
	"Netherlands":              {"Europe/Amsterdam", "America/Aruba"},
	"New Caledonia":            {"Pacific/Noumea"},
	"New Zealand":              {"Pacific/Auckland", "Pacific/Chatham", "Pacific/Fakaofo"},
	"Nicaragua":                {"America/Managua"},
	"Niger":                    {"Africa/Niamey"},
	"Nigeria":                  {"Africa/Lagos"},
	"Niue":                     {"Pacific/Niue"},
	"North Korea":              {"Asia/Pyongyang"},
	"Northern Mariana Islands": {"Pacific/Saipan"},
	"Norway":                   {"Europe/Oslo"},
	"Oman":                     {"Asia/Muscat"},
	"Pakistan":                 {"Asia/Karachi"},
	"Palau":                    {"Pacific/Palau"},
	"Palestine":                {"Asia/Gaza", "Asia/Hebron"},
	"Panama":                   {"America/Panama"},
	"Papua New Guinea":         {"Pacific/Bougainville", "Pacific/Port_Moresby"},
	"Paraguay":                 {"America/Asuncion"},
	"Peru":                     {"America/Lima"},
	"Philippines":              {"Asia/Manila"},
	"Poland":                   {"Europe/Warsaw", "Poland"},
	"Portugal":                 {"Atlantic/Azores", "Atlantic/Madeira", "Europe/Lisbon"},
	"Puerto Rico":              {"America/Puerto_Rico"},
	"Qatar":                    {"Asia/Qatar"},
	"Republic of the Congo":    {"Africa/Brazzaville"},
	"Romania":                  {"Europe/Bucharest"},
	"Russia": {
		"Asia/Anadyr", "Asia/Barnaul", "Asia/Chita", "Asia/Irkutsk", "Asia/Kamchatka",
		"Asia/Khandyga", "Asia/Krasnoyarsk", "Asia/Magadan", "Asia/Novokuznetsk",
		"Asia/Novosibirsk", "Asia/Omsk", "Asia/Sakhalin", "Asia/Srednekolymsk",
		"Asia/Tomsk", "Asia/Ust-Nera", "Asia/Vladivostok", "Asia/Yakutsk",
		"Asia/Yekaterinburg", "Europe/Astrakhan", "Europe/Kaliningrad",
		"Europe/Kirov", "Europe/Moscow", "Europe/Samara", "Europe/Saratov",
		"Europe/Simferopol", "Europe/Ulyanovsk", "Europe/Volgograd",
	},
	"Rwanda":                           {"Africa/Kigali"},
	"Saint Barthelemy":                 {"America/St_Barthelemy"},
	"Saint Helena":                     {"Atlantic/St_Helena"},
	"Saint Kitts and Nevis":            {"America/St_Kitts"},
	"Saint Lucia":                      {"America/St_Lucia"},
	"Saint Martin":                     {"America/Marigot"},
	"Saint Pierre and Miquelon":        {"America/Miquelon"},
	"Saint Vincent and the Grenadines": {"America/St_Vincent"},
	"Samoa":                            {"Pacific/Apia"},
	"San Marino":                       {"Europe/San_Marino"},
	"Sao Tome and Principe":            {"Africa/Sao_Tome"},
	"Saudi Arabia":                     {"Asia/Riyadh"},
	"Senegal":                          {"Africa/Dakar"},
	"Serbia":                           {"Europe/Belgrade"},
	"Seychelles":                       {"Indian/Mahe"},
	"Sierra Leone":                     {"Africa/Freetown"},
	"Singapore":                        {"Asia/Singapore"},
	"Sint Maarten":                     {"America/Lower_Princes"},
	"Slovakia":                         {"Europe/Bratislava"},
	"Slovenia":                         {"Europe/Ljubljana"},
	"Solomon Islands":                  {"Pacific/Guadalcanal"},
	"Somalia":                          {"Africa/Mogadishu"},
	"South Africa":                     {"Africa/Johannesburg"},
	"South Georgia and the South Sandwich Islands": {"Atlantic/South_Georgia"},
	"South Korea":              {"Asia/Seoul"},
	"South Sudan":              {"Africa/Juba"},
	"Spain":                    {"Africa/Ceuta", "Atlantic/Canary", "Europe/Madrid"},
	"Sri Lanka":                {"Asia/Colombo"},
	"Sudan":                    {"Africa/Khartoum"},
	"Suriname":                 {"America/Paramaribo"},
	"Swaziland":                {"Africa/Mbabane"},
	"Sweden":                   {"Europe/Stockholm"},
	"Switzerland":              {"Europe/Zurich"},
	"Syria":                    {"Asia/Damascus"},
	"Taiwan":                   {"Asia/Taipei"},
	"Tajikistan":               {"Asia/Dushanbe"},
	"Tanzania":                 {"Africa/Dar_es_Salaam"},
	"Thailand":                 {"Asia/Bangkok"},
	"Togo":                     {"Africa/Lome"},
	"Tonga":                    {"Pacific/Tongatapu"},
	"Trinidad and Tobago":      {"America/Port_of_Spain"},
	"Tunisia":                  {"Africa/Tunis"},
	"Turkey":                   {"Europe/Istanbul"},
	"Turkmenistan":             {"Asia/Ashgabat"},
	"Tuvalu":                   {"Pacific/Funafuti"},
	"Uganda":                   {"Africa/Kampala"},
	"Ukraine":                  {"Europe/Kiev", "Europe/Uzhgorod", "Europe/Zaporozhye"},
	"United Arab Emirates":     {"Asia/Dubai"},
	"United Kingdom": {"Europe/London", "Indian/Chagos", "America/Tortola",
		"Europe/Guernsey", "Europe/Jersey", "Europe/Isle_of_Man",
		"Pacific/Pitcairn", "America/Grand_Turk",
	},
	"United States": {
		"America/Adak", "America/Anchorage", "America/Boise", "America/Chicago",
		"America/Denver", "America/Detroit", "America/Indiana/Indianapolis",
		"America/Indiana/Knox", "America/Indiana/Marengo",
		"America/Indiana/Petersburg", "America/Indiana/Tell_City",
		"America/Indiana/Vevay", "America/Indiana/Vincennes",
		"America/Indiana/Winamac", "America/Juneau",
		"America/Kentucky/Louisville", "America/Kentucky/Monticello",
		"America/Los_Angeles", "America/Menominee", "America/Metlakatla",
		"America/New_York", "America/Nome", "America/North_Dakota/Beulah",
		"America/North_Dakota/Center", "America/North_Dakota/New_Salem",
		"America/Phoenix", "America/Sitka", "America/Yakutat",
		"Pacific/Honolulu", "Pacific/Midway", "Pacific/Wake",
		"Pacific/Pago_Pago", "Pacific/Guam",
        "America/St_Thomas",
	},
	"Uruguay":           {"America/Montevideo"},
	"Uzbekistan":        {"Asia/Samarkand", "Asia/Tashkent"},
	"Vanuatu":           {"Pacific/Efate"},
	"Vatican":           {"Europe/Vatican"},
	"Venezuela":         {"America/Caracas"},
	"Vietnam":           {"Asia/Ho_Chi_Minh", "Asia/Saigon", "Asia/Hanoi"},
	"Wallis and Futuna": {"Pacific/Wallis"},
	"Western Sahara":    {"Africa/El_Aaiun"},
	"Yemen":             {"Asia/Aden"},
	"Zambia":            {"Africa/Lusaka"},
	"Zimbabwe":          {"Africa/Harare"},
	"Myanmar":           {"Asia/Rangoon", "Asia/Yangon"},
}
